export const occupations = [
  'teacher',
  'doctor',
  'engineer',
  'lawyer',
  'accountant',
  'nurse',
  'chef',
  'writer',
  'artist',
  'musician',
  'actor',
  'programmer',
  'scientist',
  'architect',
  'salesperson',
  'marketing',
  'human resources',
  'financial analyst',
  'psychologist',
  'social worker',
  'firefighter',
  'paramedic',
  'athlete',
  'pilot',
  'entrepreneur',
  'consultant',
  'electrician',
  'plumber',
  'mechanic',
  'civil servant',
];
